### ISSUE TITLE
Node cant connect to cluster

### ISSUE THREAD

**Issue by errogaht** [codership/galera#395] opened 2016-03-24 08:09 UTC
Hello am using Galera with 10.1.12-MariaDB and SST method is xtrabackup-v2

please dont recommend SST=rsync it's not work for me 

I have healthy cluster 8 nodes, sometimes one or few nodes goes down.
im just `service mysql` start on it and they successfully connecting to cluster and all is OK.

BUT sometimes, when disconnected nodes down few days i cant connect they to cluster.

after few tries im `rm -fr /var/lib/mysql/*` & `rm -fr /var/log/mysql/*` and nothing too, they have this message in syslog:

`mysqld:  [ERROR] Binlog file '/var/log/mysql/mariadb-bin.003079' not found in binlog index, needed for recovery. Aborting.`

i know how work with this, i can recover cluster when i have nodes which can't connect to cluster with message above, so i do this:
1. shutdown all nodes, and leave only one node
2. shutdown last node and `rm -fr /var/log/mysql/*`
3. bootstrap this last node with deleted binlog
4. connect other nodes to cluster `service mysql start`
5. profit - all is OK

But problem is:

I cant down all production nodes, and down last node too, because i have 8 nodes to serve big site traffic and one running node immediately down when all traffic goes to it (of course because overload)

**QUESTION IS:**

Please help me. How connect nodes to cluster when they won't connect and have error `mysqld:  [ERROR] Binlog file '/var/log/mysql/mariadb-bin.003079' not found in binlog index, needed for recovery. Aborting.`

**Comment by ayurchen** [comment] 2016-03-28 18:26
One option is to use rsync SST method (which blocks the donor)

You may also want to report this to Percona - creators of xtrabackup - it sounds like the problem is there.

I'm closing this bug as it is not related to Galera library.

**Closed as completed by ayurchen** 2016-03-28 18:26 UTC
Labels: invalid
