### ISSUE TITLE
ist.recv_addr bind port vs donor connect to address

### ISSUE THREAD

**Issue by jayjanssen** [codership/galera#105] opened 2014-09-03 13:37 UTC
it should be possible for nodes to present a 'connect to' address/port that is different than the address/port that the joiner binds to.

**Comment by jbaramidze** [comment] 2015-09-02 13:05
any news on this? I'm trying to implement galera cluster in docker, where by default IST binds to external ip (ip of outside machine). thus it fails. I changed ist.recv_addr to 0.0.0.0, but then other peer tries to connect to 0.0.0.0 as well, and it fails again. any solutions?

**Comment by sirotopr** [comment] 2015-10-17 08:34
+1

1 year gone and no fix? This bug should take a much higher priority.
With things as they are it is impossible to run Galera behind a NAT. This is rather serious.

**Comment by sirotopr** [comment] 2015-10-18 05:26
@jbaramidze 
As a workaround, you can set the joiner's `ist.recv_addr` to its local IP address. Then, on donor nodes, set iptables rules like these:
`iptables -t nat -A PREROUTING -p tcp --dport 4568 -j DNAT --to-destination <joiner's public ip>:4568`
`iptables -A FORWARD -d <joiner's public ip> -p tcp --dport 4568 -j ACCEPT`

Run `sysctl net.ipv4.ip_forward` and check if it is set to 1. If not, edit it in `/etc/sysctl.conf` and issue a `sysctl -p`.

**Comment by stefan-langenmaier** [comment] 2015-11-29 16:53
I've had the same problem with Galera behind a NAT. I fixed it in the referenced pull request. It's working for me, maybe someone can/wants to test it.

**Comment by klausenbusk** [comment] 2016-03-04 00:20
Any update on this?

**Comment by stefan-langenmaier** [comment] 2016-03-04 00:38
The pull request is still working for me, but unfortunately I haven't got any feedback yet.

**Comment by philip-galera** [comment] 2016-03-15 10:39
Pull request https://github.com/codership/galera/pull/372 has been merged to codership/galera

**Closed by philip-galera** 2016-03-15 10:39 UTC
Labels: bug

**Comment by fragtion** [comment] 2021-06-06 23:07
This option saved me from a situation where nodes were failing to sync. The problem is that it took several hours of debugging to find the problem. Documentation and/or default configuration could be improved to put more emphasis on this potentially needing to be set/configured. With an increasing number of servers being behind some kind of NAT configuration these days, the likelihood of more people running into this issue continues to rise. I'm willing to bet that galera has lost several frustrated sysadmins who have given up due to this issue as there is nothing more frustrating than debugging a cluster with nodes that don't sync and it isn't always very obvious that the right clues can be found in /var/log/mysql/error.log

**Comment by MasterCATZ** [comment] 2023-02-11 04:11
been trying to get this working myself 

``
[Warning] [MY-000000] [Galera] Failed to prepare for incremental state transfer: Failed to open IST listener at ssl://x.x.x.x.:4568', asio error 'Failed to listen: bind:>
         at galerautils/src/gu_asio_stream_react.cpp:listen():754': 99 (Cannot assign requested address)
``

If I set the bind address to local or 0.0.0.0 this is the address the nodes then try and connect to instead of the public IP 

they see each other just fine 
donor (server with all public ports bound to it ) sees this remote server and all nodes see each other in the connection logs 

does anyone have a working example 

I am just trying to have a few remote nodes sitting off site on oracle cloud servers 

combinations I have tried with local private public IP's 

`wsrep_provider_options="socket.checksum=1;socket.ssl=yes;ist.bind_addr=`(local base_host private public)`;ist.recv_addr=`(local base_host private public)`;"`

`wsrep_node_incoming_address=`(local private public)
`wsrep_sst_receive_address=`(local private public)

`wsrep_cluster_address=gcomm://167.*.*.*`
`wsrep_node_address=192.9.*.*`
`wsrep_sst_donor="donor" `
then setting in `/etc/hosts` its Public IP address 

when ever `ist.bind_addr=` is used the `ist.recv_addr=` seems to be ignored ?

on site network is 192.168.2.* with public IP 167.*.*.*
remote network is 192.168.154.* with public IP 192.9.*.*


percona-xtradb-cluster-client_8.0.29-21-1.bullseye_amd64.deb
percona-xtradb-cluster-server_8.0.29-21-1.bullseye_amd64.deb
percona-xtradb-cluster-common_8.0.29-21-1.bullseye_amd64.deb

**Comment by williamdes** [comment] 2024-04-15 11:39
The solution I found and that works is:
```
ist.recv_addr=xxx.xxx.xxx.xxx:4568;ist.recv_bind=10.10.10.2
```
If you do not put a port in `recv_addr` it will crash the other side.
