### ISSUE TITLE
Running garb as a service fails if any paramters (but GALERA_NODES) have space characters

### ISSUE THREAD

**Issue by FelicianoTech** [codership/galera#263] opened 2015-05-03 07:55 UTC
When running nodes where wsrep_cluster_name is set to something with a space, such as "My Cluster" it runs fine.

When setting GALERA_CLUSTER="My Cluster" in /etc/default/garb, the service seems to start okay but it actually fails. Running `bash -x /etc/init.d/garb start` reveals that when run as a service, quotes aren't being places around the group name which is causing it to fail. When garb is running manually from the terminal with the quotes, it runs fine.

**Comment by ayurchen** [comment] 2015-05-03 22:53
Let's mark it as duplicate of https://github.com/codership/galera/issues/186 for accounting sake

**Closed as completed by ayurchen** 2015-05-03 22:53 UTC
Labels: duplicate

**Comment by FelicianoTech** [comment] 2015-05-05 14:59
Looks good to me. Thanks.
