### ISSUE TITLE
Galera fails to build on Debian build systems even for amd64, undefined reference to `subunit_test_start'

### ISSUE THREAD

**Issue by ottok** [codership/galera#346] opened 2015-09-16 11:16 UTC
Galera builds OK on a local sid environment and in my test builds, but for some to me unknown reason it now fails to build on official Debian build systems even for amd64.

My lucky guess is that some newer version of gcc-5 was introduced in Debian unstable this week and Galera is not compatible with it. I could be completely wrong though.

See details in downstream bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799150

**Comment by ottok** [comment] 2015-09-16 18:13
I got this tip by email, does it help you to produce a patch? I am not familiar with this library called 'check'

```
Package: src:galera-3
Followup-For: Bug #799150

Hi Otto,

just saw this on the mailing list: This issue could be caused by the new check version,
which enables subunit support.
I did not check galera's build system, but that could be caused if -lcheck is hardcoded
and not retrieved via pkg-config.

Hope this gives a pointer...

Tobi
```

**Comment by ayurchen** [comment] 2015-09-19 18:00
yes, fix is in https://github.com/codership/galera/commit/f87972c0f14f947fa646485565774034e2771760

**Comment by ayurchen** [comment] 2015-09-19 18:00
duplicate of codership/galera#321

**Closed as completed by ayurchen** 2015-09-19 18:00 UTC
Labels: duplicate
