### ISSUE TITLE
gmcast: pure virtual method called

### ISSUE THREAD

**Issue by temeo** [codership/galera#66] opened 2014-06-18 10:10 UTC
Original report: https://bugs.launchpad.net/codership-mysql/+bug/1330622

"One node in my 5-node cluster suddenly failed today with the following backtrace. I haven't seen a node go down abruptly like this before, and don't know how to reproduce:

140616 12:16:23 [Note] WSREP: (2a98992d-d6ee-11e3-a841-cfc6fbefb16b, 'tcp://0.0.0.0:4567') cleaning up duplicate 0x7fd09bc23480 after established 0x7fd09bc20780
pure virtual method called
terminate called without an active exception
140616 12:16:23 [ERROR] mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.

To report this bug, see http://kb.askmonty.org/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.

Server version: 5.5.37-MariaDB-1~trusty-wsrep-log
key_buffer_size=33554432
read_buffer_size=131072
max_used_connections=12
max_threads=502
thread_count=2
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 1134298 K bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x0x0
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0x0 thread_stack 0x48000
/usr/sbin/mysqld(my_print_stacktrace+0x2e)[0x7fd1248ebe2e]
/usr/sbin/mysqld(handle_fatal_signal+0x457)[0x7fd1244d7fa7]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340)[0x7fd122f2d340]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39)[0x7fd122583f79]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7fd122587388]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x155)[0x7fd122c796b5]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e836)[0x7fd122c77836]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e863)[0x7fd122c77863]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5f33f)[0x7fd122c7833f]
/usr/lib/galera/libgalera_smm.so(_Z4sendPN5gcomm6SocketERNS_8DatagramE+0x1f)[0x7fd1200b289f]
/usr/lib/galera/libgalera_smm.so(_ZN5gcomm6GMCast11handle_downERNS_8DatagramERKNS_13ProtoDownMetaE+0x2c4)[0x7fd1200b2f94]
/usr/lib/galera/libgalera_smm.so(_ZN5gcomm8Protolay9send_downERNS_8DatagramERKNS_13ProtoDownMetaE+0x40)[0x7fd1200ab8d0]
/usr/lib/galera/libgalera_smm.so(_ZN5gcomm3evs5Proto9send_userERNS_8DatagramEhNS_5OrderEllm+0x2a1)[0x7fd120098481]
/usr/lib/galera/libgalera_smm.so(_ZN5gcomm3evs5Proto20handle_retrans_timerEv+0x16e)[0x7fd1200a669e]
/usr/lib/galera/libgalera_smm.so(_ZN5gcomm3evs5Proto13handle_timersEv+0x1e1)[0x7fd1200a9481]
/usr/lib/galera/libgalera_smm.so(_ZN5gcomm10Protostack13handle_timersEv+0x4a)[0x7fd1200e6c4a]
/usr/lib/galera/libgalera_smm.so(_ZN5gcomm8Protonet13handle_timersEv+0x4e)[0x7fd1200e2d9e]
/usr/lib/galera/libgalera_smm.so(_Z20handle_timers_helperRN5gcomm8ProtonetERKN2gu8datetime6PeriodE+0x42)[0x7fd12010cd82]
/usr/lib/galera/libgalera_smm.so(_ZN5gcomm12AsioProtonet11handle_waitERKN4asio10error_codeE+0x55)[0x7fd12010dfb5]
/usr/lib/galera/libgalera_smm.so(_ZN4asio6detail12wait_handlerIN5boost3_bi6bind_tIvNS2_4_mfi3mf1IvN5gcomm12AsioProtonetERKNS_10error_codeEEENS3_5list2INS3_5valueIPS8_EEPFNS2_3argILi1EEEvEEEEEE11do_completeEPNS0_15task_io_serviceEPNS0_25task_io_service_operationES9_m+0xa7)[0x7fd120112b57]
/usr/lib/galera/libgalera_smm.so(_ZN4asio6detail15task_io_service3runERNS_10error_codeE+0x407)[0x7fd1201100d7]
/usr/lib/galera/libgalera_smm.so(_ZN5gcomm12AsioProtonet10event_loopERKN2gu8datetime6PeriodE+0x1a2)[0x7fd12010e1f2]
/usr/lib/galera/libgalera_smm.so(_ZN9GCommConn3runEv+0x4e)[0x7fd1201274ee]
/usr/lib/galera/libgalera_smm.so(_ZN9GCommConn6run_fnEPv+0x9)[0x7fd12012a639]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8182)[0x7fd122f25182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fd12264830d]
The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
information that should help you find out what is causing the crash.
140616 12:16:23 mysqld_safe Number of processes running now: 0
140616 12:16:23 mysqld_safe WSREP: not restarting wsrep node automatically
140616 12:16:23 mysqld_safe mysqld from pid file /var/lib/mysql/mysql.pid ended"

Maybe caused by referencing already deleted ``gmcast::Proto`` object in relay set.

**Comment by ayurchen** [comment] 2015-05-29 17:02
Closing as seemingly a duplicate of codership/galera#33

**Closed by ayurchen** 2015-05-29 17:02 UTC
Labels: duplicate
