### ISSUE TITLE
Intermediate Certificates Ignored

### ISSUE THREAD

**Issue by paescuj** [codership/galera#217] opened 2015-01-23 15:49 UTC
I was trying to encrypt the Galera group communication with an SSL wildcard certificate which is signed by some intermediate certificates.
Apparently, Galera submits only the main certificate, instead of the whole certificate chain. (Tested with the OpenSSL client). The intermediate certificates are ignored.
Therefore the opposite node can't verify the certificate and the SSL handshake can't be completed, resulting in the following log entry:
```
150123 XX:XX:XX [ERROR] WSREP: handshake with remote endpoint ssl://XX.XX.XX.XX:37059 failed: 1: 'End 
of file.' ( )
```

The main certificate and the intermediates have been concatenated into one bundled file and the correct CA file has been used.
The following SSL settings have been used:
```
wsrep_provider_options="socket.ssl_cert=<BundleCertFile>; socket.ssl_key=<KeyFile>; socket.ssl_ca=<CAFile>"
```
When using a self-signed certificate, the encryption can be established successfully.

**Comment by ayurchen** [comment] 2015-02-02 18:45
must be a duplicate of #188

**Closed** 2015-02-02 18:45 UTC
Labels: bug, duplicate
