### ISSUE TITLE
Arbitrator cannot handle the recovery file "gvwstate.dat"

### ISSUE THREAD

**Issue by fromdualjb** [codership/galera#313] opened 2015-08-07 16:31 UTC
Observed using galera-3-25.3.10-2.el6.x86_64.rpm:

I understand that by default, "garbd" should maintain "gvwstate.dat" and use it for fast recovery. However, this doesn't work, the log file contains:
  WARN: open file(./gvwstate.dat.tmp) failed(Permission denied)

This doesn't surprise me, because of the way "garbd" is started:
The user is "nobody", and the run directory is unspecified.
According to its entry in my "/proc/PID/cwd", it is "/", where only "root" may create files.

IMO, there should be a mechanism that enforces "garbd" to run in some well-defined directory (other than "/tmp", so that files survive the reboot) in which "nobody" has write permissions, so that the file can be created.
(As an alternative, introduce some other user for the arbitrator. Within a MySQL setup, you might as well create user "mysql" and let "garbd" run in ~mysql.)

**Comment by philip-galera** [comment] 2015-08-11 05:44
I have checked the source code and indeed the "." directory is hard-coded in garbd (COMMON_BASE_DIR_DEFAULT). So it seems that the way to fix this is in the init script.

**Comment by philip-galera** [comment] 2015-09-10 13:48
Duplicate issue https://github.com/codership/galera/issues/345

**Comment by cjbirk** [comment] 2015-10-05 22:22
Why doesn't this get fixed instead of telling people to change the init script.

**Comment by hal58th** [comment] 2015-10-13 00:37
I echo @cjbirk. Seems kinda ridiculous that there is 3 duplicates of this bug but still no real solution.

**Comment by vmalaga** [comment] 2016-05-29 19:09
Hi 7 months more and there is no solution for this bug.

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
```

```
root@myarbitrator:~# garbd -v
 INFO: 3.15.r8459459
```

**Comment by ottok** [comment] 2016-09-25 04:37
I also noticed this on Ubuntu 14.04 with latest Galera 3.17 installed. Tried to inject cd-commands into /etc/init.d/garb but with no success yet. In my opinion it would be smart for this to default to `/var/lib/garb` and write there just as all other servers by convetion do.

**Comment by rgpublic** [comment] 2017-08-16 09:54
OK, do I understand correctly, that Galera Arbitrator is simply not in a usable state on Ubuntu at the moment, right?

**Comment by ottok** [comment] 2017-08-16 10:26
I have garbd running successfully and this is how my /etc/default/garb looks like:

```

$ cat /etc/default/garb
# A comma-separated list of node addresses (address[:port]) in the cluster
GALERA_NODES="10.8.8.147:4567 10.8.8.151:4567"

# Galera cluster name, should be the same as on the rest of the nodes.
GALERA_GROUP="<redacted>"

# Optional Galera internal options string (e.g. SSL settings)
# see http://galeracluster.com/documentation-webpages/galeraparameters.html
# GALERA_OPTIONS=""

# Log file for garbd. Optional, by default logs to syslog
#LOG_FILE="/var/log/garb.log"

# Working directory. Optional, by default cwd to /
CHDIR="/var/lib/garb"
cd $CHDIR

```

As I suggested above, I think the software should default to `/var/lib/garb` if no CHDIR is defined.

**Comment by rgpublic** [comment] 2017-08-16 17:11
Thanks @ottok - I tried to change the file to look exactly like yours, added CHDIR etc. But to no avail. I get this:

{code}
Aug 16 19:05:59 tukan1 garb[5715]:  * Starting /usr/bin/garbd:
Aug 16 19:05:59 tukan1 garbd[5729]: CRC-32C: using hardware acceleration.
Aug 16 19:05:59 tukan1 garbd[5729]: Read config: 
                                            name:    garb
Aug 16 19:05:59 tukan1 garbd[5732]: protonet asio version 0
Aug 16 19:05:59 tukan1 garbd[5732]: Using CRC-32C for message checksums.
Aug 16 19:05:59 tukan1 garbd[5732]: backend: asio
Aug 16 19:05:59 tukan1 garbd[5732]: gcomm thread scheduling priority set to other:0
Aug 16 19:05:59 tukan1 garbd[5732]: access file(./gvwstate.dat) failed(No such file or directory)
Aug 16 19:05:59 tukan1 garbd[5732]: restore pc from disk failed
Aug 16 19:05:59 tukan1 garbd[5732]: GMCast version 0
Aug 16 19:05:59 tukan1 garbd[5732]: (2d429e72, 'tcp://0.0.0.0:4567') listening at tcp://0.0.0.0:4567
Aug 16 19:05:59 tukan1 garbd[5732]: (2d429e72, 'tcp://0.0.0.0:4567') multicast: , ttl: 1
Aug 16 19:05:59 tukan1 garbd[5732]: EVS version 0
Aug 16 19:05:59 tukan1 garbd[5732]: gcomm: connecting to group 'tukan_cluster', peer '192.168.0.1:4567,192.168.0.2:4567'
Aug 16 19:05:59 tukan1 garbd[5732]: bind: Address already in use
Aug 16 19:05:59 tukan1 garbd[5732]: failed to open gcomm backend connection: 98: error while trying to listen 'tcp://0.0.0.0:4567?socket.non_blocking=1', asio error 'bind: Address already in use': 98 (Address already in use)
Aug 16 19:05:59 tukan1 garbd[5732]: gcs/src/gcs_core.cpp:gcs_core_open():208: Failed to open backend connection: -98 (Address already in use)
Aug 16 19:05:59 tukan1 garbd[5732]: gcs/src/gcs.cpp:gcs_open():1404: Failed to open channel 'tukan_cluster' at 'gcomm://192.168.0.1:4567,192.168.0.2:4567': -98 (Address already in use)
Aug 16 19:05:59 tukan1 garbd[5732]: Exception in creating receive loop: Failed to open connection to group: 98 (Address already in use)
                                             at garb/garb_gcs.cpp:Gcs():35
Aug 16 19:06:00 tukan1 garb[5715]:    ...fail!
Aug 16 19:06:00 tukan1 systemd[1]: garb.service: Control process exited, code=exited status=1
-- Subject: Unit garb.service has failed
-- Unit garb.service has failed.
Aug 16 19:06:00 tukan1 systemd[1]: garb.service: Unit entered failed state.
Aug 16 19:06:00 tukan1 systemd[1]: garb.service: Failed with result 'exit-code'.
{code}

What's also confusing me is the GALERA_NODES variable. In the comment it says "A comma-separated list". But in your example it's space-separated. Does this matter? I've seen some people even write it with the gcomm:// prefix. What I already found out is that the port is required. Even though in the comment it says "[:port]" where the square brackets usually mean "optional". 

And I wonder what "Address already in use" means in above error message. Of course the address is already in use. It's used by the Galera nodes. That's why I specified those IPs. Weird.

Seems astonishingly difficult to set this up properly... Any help is much appreciated.

**Comment by evgenbn** [comment] 2018-09-07 11:36
Same error in version 3.26.rac090bc installed from percona-xtradb-cluster-garbd-5.7 package.
Ат [PXC-1883](https://jira.percona.com/browse/PXC-1883) proposed a patch that creates a directory /var/lib/galera/ and it is indeed created and assigned rw rights to the nobody user. But apparently garbd continues to try to use /.
How do I specify a working directory for garbd?

**Comment by evgenbn** [comment] 2018-09-07 12:10
Solved. I found at https://bugs.launchpad.net/percona-xtradb-cluster/+bug/1531842/comments/5. Just add

GALERA_OPTIONS="base_dir=/var/lib/galera/"

to /etc/default/garbd and restart garbd.

**Comment by Alwaysin** [comment] 2019-02-19 10:17
Changing /etc/init.d/garb or /etc/default/garb has no effects for me on Debian 9.
Only thing working is to change nobody to root so that it can write in / but I'd like to avoid that!

**Comment by mr-smit** [comment] 2019-03-05 15:17
just chmod 777 /

**Comment by emcepe** [comment] 2021-02-06 00:44
Now its 2021, newest garbd installed and the Bug is still not fixed :-(
Muahahahhahhahahha :-(((

**Comment by rgpublic** [comment] 2021-02-09 10:45
Since this bug still isn't fixed and #442 is a wontfix, I've resorted to a different solution in the meantime: I just have a third server that periodically runs a remote command via a timeout-limited ssh to check whether both servers are still alive and reachable. If only one mysql is running and it is non-primary it just bootstraps that node via 

`SET GLOBAL wsrep_provider_options="pc.bootstrap=1";`

The big advantage is: The third server can be somewhere else and you neither have all the traffic running through it nor do you have to setup traffic encryption just for this. It's a lean and simple solution and saves you from all the hassle with garbd. It seems it isn't too well supported considering this longstanding bug here. Perhaps this is an idea/approach that's also helpful for others, that's why I'm mentioning it here.

**Comment by emcepe** [comment] 2021-02-26 22:00
@rgpublic: mind sharing your script?
I could for sure invent the wheel again but ... :-)

**Comment by rgpublic** [comment] 2021-02-27 17:16
@emcepe: I'd love to but it is too deeply intertwined with proprietary company stuff I can't share. I'm currently reworking it though and will share it here as soon as it is available as a separate BASH script.

**Comment by canepan** [comment] 2021-04-20 09:11
It looks like the issue is the missing port specification after the node IPs.
See also https://bugs.launchpad.net/percona-xtradb-cluster/+bug/1503349

**Comment by redochka** [comment] 2021-08-11 09:45
When adding `GALERA_OPTIONS="base_dir=/var/lib/galera/"` to `/etc/default/garb`

I get:

```
ERROR: Unrecognized parameter 'base_dir'
```

By the way, no offense intended, but what a stupid idea to choose a filename without an extension: `/etc/default/garb`

**Comment by temeo** [comment] 2022-05-25 09:34
As of Galera 3.37/4.12, garbd recognizes parameters `-w`, `--workdir` which can be used to set the working directory for garbd process. Corresponding `WORK_DIR` parameter was added into startup scripts.

**Closed as completed by temeo** 2022-05-25 09:34 UTC
Labels: bug
