### ISSUE TITLE
Exception after eviction of node and hung shutdown

### ISSUE THREAD

**Issue by ronin13** [codership/galera#196] opened 2014-12-05 15:31 UTC
```
Version: '5.6.21-70.0-25.8-debug'  socket: '/pxc56/datadir2/pxc.sock'  port: 5000  Percona XtraDB Cluster (GPL) -25.8, Revision 919, wsrep_25.8.r919
2014-12-05 19:17:01 7006 [Note] WSREP: (2ec2260c, 'tcp://127.0.0.1:5010') turning message relay requesting off
2014-12-05 19:19:58 7006 [Note] WSREP: (2ec2260c, 'tcp://127.0.0.1:5010') turning message relay requesting on, nonlive peers: tcp://127.0.0.1:4010
2014-12-05 19:19:59 7006 [Note] WSREP: (2ec2260c, 'tcp://127.0.0.1:5010') reconnecting to 34c21f9f (tcp://127.0.0.1:4010), attempt 0
2014-12-05 19:19:59 7006 [Warning] WSREP: handshake with 34c21f9f tcp://127.0.0.1:4010 failed: 'evicted'
2014-12-05 19:19:59 7006 [Warning] WSREP: handling gmcast protocol message failed: this node has been evicted out of the cluster, gcomm backend restart is required (FATAL)
        at gcomm/src/gmcast_proto.cpp:handle_failed():208
2014-12-05 19:19:59 7006 [ERROR] WSREP: exception from gcomm, backend must be restarted: this node has been evicted out of the cluster, gcomm backend restart is required (FATAL)
        at gcomm/src/gmcast_proto.cpp:handle_failed():208
2014-12-05 19:19:59 7006 [Note] WSREP: gcomm: terminating thread
2014-12-05 19:19:59 7006 [Note] WSREP: gcomm: joining thread
2014-12-05 19:19:59 7006 [Note] WSREP: gcomm: closing backend
2014-12-05 19:19:59 7006 [Note] WSREP: Forced PC close
2014-12-05 19:19:59 7006 [Note] WSREP: gcomm: closed
2014-12-05 19:19:59 7006 [ERROR] WSREP: gcs/src/gcs_core.cpp:ssize_t core_handle_comp_msg(gcs_core_t*, gcs_recv_msg*, gcs_act*)():717: Malformed component message. Ignoring
^\2014-12-05 19:22:23 7006 [Note] /pxc56d/bin/mysqld: Normal shutdown

2014-12-05 19:22:23 7006 [Note] WSREP: Stop replication
2014-12-05 19:22:23 7006 [Note] WSREP: Provider disconnect
2014-12-05 19:22:23 7006 [Note] WSREP: Closing send monitor...
2014-12-05 19:22:23 7006 [Note] WSREP: Closed send monitor.
2014-12-05 19:22:23 7006 [Warning] WSREP: gcomm: backend already closed
```

I was able to reproduce this with following setup

i) Node A and Node B 

ii) Evict node B from node A with evs.evict=gcomm_uuid_nodeB

iii) Shutdown node B

iv) Start node B again and let it sync

v) Evict node B again, it produces the error:

```
2014-12-05 19:19:59 7006 [ERROR] WSREP: gcs/src/gcs_core.cpp:ssize_t core_handle_comp_msg(gcs_core_t*, gcs_recv_msg*, gcs_act*)():717: Malformed component message. Ignoring
```

vi) Try to shutdown now with SIGQUIT (^): it hangs. SIGTERM also fails to 
shutdown.

Backtraces: https://gist.github.com/38449a9e43e6fb2ce2ae

**Comment by temeo** [comment] 2018-02-26 11:06
Seems to be duplicate of https://github.com/codership/galera/issues/500, closing this one.

**Closed by temeo** 2018-02-26 11:06 UTC
