### ISSUE TITLE
Sign Galera releases with OpenPGP

### ISSUE THREAD

**Issue by ottok** [codership/galera#341] opened 2015-09-06 17:59 UTC
Offcial Galera releases should be signed to ensure authenticity. At minimum at least the source file should be signed and a .asc file found at http://releases.galeracluster.com/source/

For comparison see how ftp://ftp.osuosl.org/pub/mariadb/mariadb-10.0.21/source/ contains both mariadb-10.0.21.tar.gz and mariadb-10.0.21.tar.gz.asc

For example Debian employs automated signature checking: https://wiki.debian.org/debian/watch#Cryptographic_signature_verification

It would be nice if the source release signature is made with the same key already advertised at http://releases.galeracluster.com/GPG-KEY-galeracluster.com

**Comment by philip-galera** [comment] 2015-09-07 05:03
Closing https://github.com/codership/QA/issues/69 as a duplicate of this ticket.

**Comment by philip-galera** [comment] 2015-09-07 05:39
Otto, we have created a step in our build system that will produce the .asc files using the GPG-KEY-galeracluster.com key . So the sources for the next release will be signed.

The command that will be used is

```
gpg --batch --armor --detach-sign
```

Is that the correct command? Is there anything else that we should do on our end?

Thank you.

**Comment by ottok** [comment] 2015-09-07 05:42
Yes, that command is correct. Verification is done with `gpg --verify ABC.asc`

**Comment by philip-galera** [comment] 2015-09-07 05:59
gpg --verify works for me . If there is nothing else that needs to be done on our side, I will close this ticket.

**Comment by philip-galera** [comment] 2015-09-07 06:31
I am reopening this ticket as we need to reorganize the scripts that are used a bit.

**Comment by philip-galera** [comment] 2015-09-07 10:24
The signing part is now a script that has been pushed to the QA repository, so closing the ticket for good.

**Closed as completed by philip-galera** 2015-09-07 10:24 UTC
Labels: enhancement
