### ISSUE TITLE
ifconfig does wrong guessing on CentOS 7

### ISSUE THREAD

**Issue by shinguz** [codership/galera#223] opened 2015-02-09 20:53 UTC
2015-02-09 21:35:52 2953 [ERROR] WSREP: Process completed with error: /sbin/ifconfig | grep -E '^[[:space:]]+inet addr:' | grep -m1 -v 'inet addr:127' | sed 's/:/ /' | awk '{ print $3 }': 2 (No such file or directory)
2015-02-09 21:35:52 2953 [Warning] WSREP: access file(gvwstate.dat) failed(No such file or directory)

Workaround: Specify explicitly:
wsrep_node_address             = 192.168.56.101
wsrep_node_incoming_address    = 192.168.56.101
wsrep_sst_receive_address      = 192.168.56.101

Fix: This should do the job
/sbin/ifconfig | grep -E '^[[:space:]]+inet ' | grep -m1 -v 'inet 127' | awk '{ print $2 }'
10.0.2.15

[root@centos7tpl mysql]# /sbin/ifconfig | grep -E '^[[:space:]]+inet addr:'
[root@centos7tpl mysql]# ifconfig
enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fe4b:d490  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:4b:d4:90  txqueuelen 1000  (Ethernet)
        RX packets 9  bytes 1816 (1.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 62  bytes 9208 (8.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 08:00:27:a0:80:5e  txqueuelen 1000  (Ethernet)
        RX packets 1056  bytes 105234 (102.7 KiB)
        RX errors 0  dropped 14  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s9: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.56.101  netmask 255.255.255.0  broadcast 192.168.56.255
        inet6 fe80::a00:27ff:fedf:309  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:df:03:09  txqueuelen 1000  (Ethernet)
        RX packets 689  bytes 68728 (67.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 477  bytes 113828 (111.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by ayurchen** [comment] 2015-02-09 21:36
1. Oli, are you sure that setting only
  ```
wsrep_node_address = 192.168.56.101
  ```
  is not enough? (Because that would be a bug)
  2. Node IP autoguessing is not a supported feature, it is provided on as is basis. And your suggestion results in the following on Ubuntu (which is wrong, you need a pure IP address):
```
             $ /sbin/ifconfig | grep -E '^[[:space:]]+inet ' | grep -m1 -v 'inet 127' | awk '{ print $2 }'
             addr:10.21.32.1
```

**Comment by ayurchen** [comment] 2015-02-09 21:46
Finally this is a mysql-wsrep issue and is a duplicate of https://github.com/codership/mysql-wsrep/issues/45, discussion should be moved there.

**Closed by ayurchen** 2015-02-09 21:46 UTC
